config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  namespace :admin do
    resources :users do
      resources :products
      resources :videos
      resources :photos
      resources :ratings
      resources :companies
      resources :reviews
    end
    resources :father_categories do
      resources :categories
    end
    resources :categories do
      resources :sub_categories
      resources :photos
      resources :videos
      resources :users
    end
    resources :sub_categories do
      resources :products
    end
    resources :companies do
      resources :products
      resources :users
    end
    resources :products do
      resources :videos
      resources :photos
      resources :prices
      resources :ratings
      resources :reviews
      resources :users
    end
    resources :videos do
      resources :users
    end
    resources :photos do
      resources :users
    end
    resources :distributors do
      resources :companies
    end
  end

  root to: 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users do
    collection do
      get :review
      get :photo
      get :video
    end
  end
  get 'ajax_destroy_recent_search', to: 'users#ajax_destroy_recent_search', as: :ajax_destroy_recent_search
  get 'ajax_destroy_favourite', to: 'users#ajax_destroy_favourite', as: :ajax_destroy_favourite
  get 'ajax_destroy_all_favourites', to: 'users#ajax_destroy_all_favourites', as: :ajax_destroy_all_favourites
  get 'ajax_destroy_recent_searches', to: 'users#ajax_destroy_recent_searches', as: :ajax_destroy_recent_searches
  get 'ajax_get_filter_options/:id' => 'products#set_filter_options', as: :set_filter_options

  resources :home, only: [:index]
  resources :search, only: [:index]
  resources :sub_categories, only: [:show]
  resources :products, only: [:show] do
    resources :reviews, only:[:new, :create], defaults: {format: :json}
    resources :user_favourite_products, only:[:add, :remove] do
      collection do
        get 'add'
        get 'remove'
      end
    end
  end

  resource :pictures, format: false, only: :create
  resources :photos, format: false, only: [:create, :show]
  resources :videos, format: false, only: [:create, :show]

  # controller :favourites, as: :favourite, path: :favourites,
  #            format: true, constraints: { format: :json } do
  #   %i(products photos videos).each do |type|
  #     defaults type: type do
  #       post type, to: :create
  #       delete type, to: :destroy
  #     end
  #   end
  # end

  post '/modals/:action', controller: :modals, format: false, as: :modals
  get '/modals/fetch' => 'modals#fetch', format: :json
end

app/models/video.rb
class Video < ActiveRecord::Base
  include Recentable

  HOSTS = {
    'youtube' => [/^.*(?:youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/,
                  'https://www.youtube.com/embed/#{code}'],
    'vimeo'   => [/\/\/(?:www\.)?vimeo.com\/(\d+)(?:$|\/|\?)/,
                  'https://player.vimeo.com/video/#{code}'],
  }.freeze
  HOSTS.each_value do |host_params|
    host_params.freeze
    host_params.each { |host_param| host_param.freeze }
  end

  attr_accessor :company_id

  validates :host, inclusion: { in: HOSTS.keys }, if: :url_changed?
  before_validation :adjust_url, if: :url_changed?

  belongs_to :category
  belongs_to :product
  belongs_to :user

  has_many :user_favourites, as: :favouriteable
  has_many :users, through: :user_favourites
  has_one :picture, as: :imageable

  accepts_nested_attributes_for :picture, allow_destroy: true

  def self.add_billet
    new main: false, day: false
  end

  def self.last_videos(except:, limit:)
    all.where.not(id: except.id).order(created_at: :desc).limit(limit)
  end

  private

  def url_changed?
    changed.include? 'url'
  end

  def adjust_url
    self.host, self.code = nil, nil

    HOSTS.each do |host, host_params|
      url_regexp, url_pattern = host_params
      if matchdata = url.match(url_regexp)

        self.host, self.code = host, matchdata[1]
        self.url = url_pattern.gsub '#{code}', code

        return
      end
    end

    nil
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  include ImitateDelay
  imitate_delay only: :create
  before_action :set_video, only:[:show]
  before_action :set_product, only:[:show]

  def show
    @more_videos = @product.videos.last_videos(except:@video, limit:7)
  end

  def create
    video = Video.new creation_params.merge! main: false, day: false, user: current_user
    if video.save
      redirect_to :back
    else
      render 'shared/errors', locals: { errors: video.errors }
    end
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def set_product
    @product = @video.product
  end

  def creation_params
    params.require(:video).permit %i(url title comment product_id category_id)
  end
end

app/views/videos/_add.html.erb
<%= addendum_storage 'video' %>

<%= form_for Video.add_billet, url: videos_path, html: { class: 'form-horizontal' } do |form| %>

  <%= render 'shared/selects', f: form %>

  <div class='form-group'>
    <%= form.label :url, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= form.text_field :url, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= form.label :comment, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= form.text_area :comment, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <div class='col-sm-offset-2 col-sm-10'>
      <%= form.submit class: 'btn btn-primary', id:'submit-video', style:'display:none;' %>
    </div>
  </div>

<% end %>

<% content_for :action do %>
  <%= link_to "Upload", '#', class:'btn upload-button', data:{submit_button:true, submit_target:'#submit-video'} %>
<% end %>

app/views/videos/_breadcrumbs.html.erb
<ol class='breadcrumb'>
  <li>
    <%= link_to 'Home', root_path %>
  </li>
  <li>
    <%= link_to product.sub_category_name,
                search_index_path(sub_categories: [product.sub_category_id]) %>
  </li>
  <li>
    <%= link_to product.company_name,
                search_index_path(sub_categories: [product.sub_category_id],
                                  companies: [product.company_id]) %>
  </li>
  <li class='active'>
    <%= product.name %>
  </li>
</ol>

app/views/videos/_search_thumbnail.html.erb
<div class='thumb-wrapper'>
  <div class='flex thumb-header'>
    <span class='thumb-header-abbr'>
      <%=video.product && video.product.company && video.product.company.name %>
    </span>
    <span class='thumb-time-date'>
      <span class='glyphicon glyphicon-time'></span>
      <span>
        <%= video.created_at.strftime("%d %b %H:%M") %>
      </span>
    </span>
  </div>
    <div class='embed-responsive embed-responsive-16by9'>
      <%= link_to video do%>
        <div class="media-overlay"></div>
        <iframe class='embed-responsive-item' src='<%= video.url %>'></iframe>
      <% end %>
    </div>
    <div class='flex thumb-footer'>
      <span class='thumb-footer-model'>
        <%= link_to video.product do %>
          <%= video.product.name%> <%= "(#{video.product.year})" if video.product.year%>
        <% end %>
      </span>
      <div class='thumb-star-wrapper'>
        <%= render 'products/rating', rating: video.product.rating %>
      </div>
    </div>
    <div class='thumb-description text-left'>
      <p>
        <%= truncate video.comment, length: 110, separator: ' ' %>
      </p>
    </div>
    <div class='thumb-moreinfo-link'>
      <%= link_to 'More Info...', video.product %>
    </div>
</div>

app/views/videos/_thumbnail.html.erb
<div class='thumb-wrapper'>
  <%= link_to video do %>
    <div class='embed-responsive embed-responsive-16by9'>
      <div class="media-overlay"></div>
      <iframe class='embed-responsive-item' src='<%= video.url %>'></iframe>
    </div>
  <% end %>
  <div class='thumb-description text-center'>
    <%=truncate video.comment, length: 110, separator: ' '%>
  </div>
</div>

app/views/videos/show.html.erb
<div class='main-container'>
  <main class='main-content-wrapper'>
    <%= render partial:'products/breadcrumbs', locals: { product: @product } %>
    <div class='container-fluid'>
      <div class='row'>
        <div class='col-xs-10 col-xs-offset-1'>
          <div class='embed-responsive embed-responsive-16by9'>
            <iframe class='embed-responsive-item' src='<%= @video.url %>'></iframe>
          </div>
        </div>
      </div>
      <div class='row media-info'>
        <div class='col-xs-10 col-xs-offset-1'>

          <div class="media-description">
            <p><%= @video.comment%></p>
          </div>

          <div class="media-share">
            <ul class="list-inline">
              <li><strong>Share this video</strong></li>
              <li><a href="#"><%=image_tag asset_path('twitter_img_small.png')%></a></li>
              <li><a href="#"><%=image_tag asset_path('facebook_img_small.png')%></a></li>
            </ul>
          </div>

          <% if @more_videos.any? %>
          <div class="more-media">
            <div class="more-media-title">
              <h2>More <%= @product.name %> Videos</h2>
            </div>
            <%= render partial:'videos/show/more_videos', locals: {videos: @more_videos} %>
          </div>
          <% end %>

        </div>
      </div>
    </div>
  </main>
</div>