config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  namespace :admin do
    resources :users do
      resources :products
      resources :videos
      resources :photos
      resources :ratings
      resources :companies
      resources :reviews
    end
    resources :father_categories do
      resources :categories
    end
    resources :categories do
      resources :sub_categories
      resources :photos
      resources :videos
      resources :users
    end
    resources :sub_categories do
      resources :products
    end
    resources :companies do
      resources :products
      resources :users
    end
    resources :products do
      resources :videos
      resources :photos
      resources :prices
      resources :ratings
      resources :reviews
      resources :users
    end
    resources :videos do
      resources :users
    end
    resources :photos do
      resources :users
    end
    resources :distributors do
      resources :companies
    end
  end

  root to: 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users do
    collection do
      get :review
      get :photo
      get :video
    end
  end
  get 'ajax_destroy_recent_search', to: 'users#ajax_destroy_recent_search', as: :ajax_destroy_recent_search
  get 'ajax_destroy_favourite', to: 'users#ajax_destroy_favourite', as: :ajax_destroy_favourite
  get 'ajax_destroy_all_favourites', to: 'users#ajax_destroy_all_favourites', as: :ajax_destroy_all_favourites
  get 'ajax_destroy_recent_searches', to: 'users#ajax_destroy_recent_searches', as: :ajax_destroy_recent_searches
  get 'ajax_get_filter_options/:id' => 'products#set_filter_options', as: :set_filter_options

  resources :home, only: [:index]
  resources :search, only: [:index]
  resources :sub_categories, only: [:show]
  resources :products, only: [:show] do
    resources :reviews, only:[:new, :create], defaults: {format: :json}
    resources :user_favourite_products, only:[:add, :remove] do
      collection do
        get 'add'
        get 'remove'
      end
    end
  end

  resource :pictures, format: false, only: :create
  resources :photos, format: false, only: [:create, :show]
  resources :videos, format: false, only: [:create, :show]

  # controller :favourites, as: :favourite, path: :favourites,
  #            format: true, constraints: { format: :json } do
  #   %i(products photos videos).each do |type|
  #     defaults type: type do
  #       post type, to: :create
  #       delete type, to: :destroy
  #     end
  #   end
  # end

  post '/modals/:action', controller: :modals, format: false, as: :modals
  get '/modals/fetch' => 'modals#fetch', format: :json
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :products, inverse_of: :sub_category
  has_many :filters
  has_many :filter_options, through: :filters
  has_one :picture, as: :imageable
  has_many :companies, through: :products
  has_many :prices, through: :products

  accepts_nested_attributes_for :filters, allow_destroy: true
  accepts_nested_attributes_for :picture

  delegate :url, to: :picture, prefix: true, allow_nil: true # .picture_url
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def show
    @sub_category = SubCategory.find(params[:id])
    @products = @sub_category.products.filter(params[:filters])
                                      .companies(params[:companies])
                                      .year_from(params[:year_from])
                                      .year_to(params[:year_to])
                                      .price_from(params[:price_from])
                                      .price_to(params[:price_to])
    @filters = @sub_category.filters

    respond_to do |format|
      format.js { render 'success', layout: false }
      format.html
    end
  end
end

app/views/sub_categories/_breadcrumbs.html.erb
<ol class='breadcrumb cover'>
  <li>
    <%= link_to 'Home', root_path %>
  </li>
  <li class='active'>
    <%= link_to @sub_category.name, @sub_category %>
  </li>
</ol>

app/views/sub_categories/_category_filter.html.erb
<div class="filter-wrapper">
  <%= search_category_link category, params[:sub_categories]  do %>
    <label class="checkbox-style">
      <input id="<%= "category-#{category.id}" %>" type="checkbox" class="checkbox-inline" <%= category.searched_for?( params[:sub_categories]) ? "checked='checked'" : "" %>>
        <% if category.searched_not_for_all?( params[:sub_categories] ) %>
          <span class="dash"></span>
        <% else %>
          <span></span>
        <% end %>
    </label>
    <label for="<%= "category-#{category.id}" %>" class="filter-name"><%= category.name %></label>
  <% end %>
    <% if category.searched_for?( params[:sub_categories]) %>
      <span class="filter-plus-icon glyphicon glyphicon-plus glyphicon-minus"></span>
      <div class="sub-filter-wrapper display">
    <% else %>
      <span class="filter-plus-icon glyphicon glyphicon-plus"></span>
      <div class="sub-filter-wrapper">
    <% end %>
    <% category.sub_categories.each do |sub_cat| %>
        <%= search_sub_category_link( sub_cat, params[:sub_categories] ) do %>
        <label class="checkbox-style">
          <input id="<%= "category-#{sub_cat.id}" %>"
                 type="checkbox"
                 class="checkbox-inline"
                 <%= params[:sub_categories].is_a?(Array) && params[:sub_categories].include?(sub_cat.id.to_s) ? "checked='checked'" : "" %>>
            <span></span>
        </label>
        <label for="<%= "category-#{sub_cat.id}" %>" class="filter-name"><%= sub_cat.name %></label>
      <% end %>
    <% end %>
    </div>
</div>

app/views/sub_categories/_company_filter.html.erb
<div class="filter-wrapper">
    <a class='sub-filter-checkbox'>
      <label class="checkbox-style">

        <%= check_box_tag "companies[]", company.id,
                                       params[:companies] && params[:companies].include?(company.id.to_s),
                                       :id => "checkbox_com_" + company.id.to_s,
                                       :class => "check__form" %>
      </label>
      <label for="<%= "checkbox_com_#{company.id}" %>" class="filter-name"><%= company.name %></label>
    </a>
</div>

app/views/sub_categories/_filter_options.html.erb
<div class="filter-wrapper">
    <a class='sub-filter-checkbox'>
      <label class="checkbox-style">

        <%= check_box_tag "filters[]", option.id,
                                       params[:filters] && params[:filters].include?(option.id.to_s),
                                       :id => "checkbox_" + option.id.to_s,
                                       :class => "check__form" %>
      </label>
      <label for="<%= "checkbox_#{option.id}" %>" class="filter-name"><%= option.name %></label>
    </a>
</div>

app/views/sub_categories/_filters_header.html.erb
<div class="background-wrapper" style="<%= sub_category_cover(@sub_category) %>">
    <%= render 'breadcrumbs' %>
    <div class="flex main-heading-wrapper">
        <h1 class="main-heading"><%= @sub_category.name %></h1>
        <span class="heading-sub-text">Use the filters to find your perfect</span>
    </div>
    <div class="main-menu-wrapper">
        <nav class="flex">
            <a href="#">Feature</a>
            <a href="#">Video del dla</a>
            <a href="#">Photo of the Day</a>
            <a href="#">Video</a>
            <a href="#">Video</a>
            <a href="#">Feature</a>
        </nav>
    </div>
</div>

app/views/sub_categories/_left_filter.html.erb
<div class="filter-group <%= filter_type %>" data-type="<%= filter_type %>">
  <div class="filter-heading-wrapper">
    <span class="filter-group-icon <%= icon_class %>" aria-hidden="true"></span>
    <span class="filter-group-heading"><%= filter_name %></span>
    <span class="filter-group-arrow glyphicon glyphicon-play"></span>
  </div>
  <div class="filter-group-contents">
    <%= yield %>
  </div>
  <div class="showmore-link-wrapper">
    <span class="invisible-span"></span>
    <span class="more-link">More...</span>
    <span class="invisible-span"></span>
  </div>
</div>

app/views/sub_categories/_left_filters.html.erb
<aside class="side-panel-wrapper search-side-panel side-panel-wrapper-fix">
  <% if user_signed_in? %>

    <%= render layout: 'left_filter',
        locals: { filter_name: 'Favourites', filter_type: 'favourites', icon_class: 'glyphicon glyphicon-star' } do %>
      <% current_user.favourite_products.last(10).each do |product| %>
        <div class="filter-wrapper">
            <span class="glyphicon glyphicon-trash"></span>
            <span class="filter-name">
              <%= link_to product.name, product %>
            </span>
        </div>
      <% end  %>
    <% end %>

    <%= render layout: 'left_filter',
        locals: { filter_name: 'History Search', filter_type: 'history-search', icon_class: 'glyphicon glyphicon-search' } do %>
      <% current_user.searches.recent.each do |search| %>
      <div class="filter-wrapper">
        <%= search_link [ param_change( :update, :delete_search, search.id) ] do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end  %>
          <span class="filter-name">
            <%= search_link search.text, [ param_change( :update, :search, search.text) ] %>
          </span>
      </div>
      <% end %>
    <% end %>
  <% end %>

  <%= form_tag(sub_category_path(@sub_category, format: :js), method: 'get', id: 'filter_form', remote: true) do %>


    <%= render layout: 'left_filter',
        locals: { filter_name: 'Year', filter_type: 'year', icon_class: 'glyphicon glyphicon-plane' } do %>
        <%= render partial: 'year_filter', locals: { years: @sub_category.products.map {|p| p.year}.uniq } %>
    <% end %>

    <%= render layout: 'left_filter',
        locals: { filter_name: 'Price', filter_type: 'prive', icon_class: 'glyphicon glyphicon-plane' } do %>
        <%= render partial: 'price_filter', locals: { prices: @sub_category.prices.map {|p| p.amount}.uniq } %>
    <% end %>

    <%= render layout: 'left_filter',
        locals: { filter_name: 'International Brands', filter_type: 'international-brands', icon_class: 'glyphicon glyphicon-plane' } do %>
      <% @sub_category.companies.international(@user_country).uniq.each do |company| %>
        <%= render partial: 'company_filter', locals: { company: company } %>
      <% end %>
    <% end %>

    <%= render layout: 'left_filter',
        locals: { filter_name: 'Local Brands', filter_type: 'international-brands', icon_class: 'glyphicon glyphicon-plane' } do %>
      <% @sub_category.companies.local(@user_country).uniq.each do |company| %>
        <%= render partial: 'company_filter', locals: { company: company } %>
      <% end %>
    <% end %>

    <% @filters.each do |filt| %>
      <%= render layout: 'left_filter',
          locals: { filter_name: filt.name, filter_type: filt.name, icon_class: 'glyphicon glyphicon-home' } do %>
        <% filt.filter_options.each do |option| %>
          <%= render partial: 'filter_options', locals: { option: option } %>
        <% end %>
      <% end %>
    <% end %>

  <% end %>



</aside>

app/views/sub_categories/_price_filter.html.erb
<div class="filter-wrapper">
    <a class='sub-filter-checkbox'>
      <div id="slider">
        <%= hidden_field_tag 'price_from', :onchange => "$(this).closest('form').submit();" %>
        <%= hidden_field_tag 'price_to', :onchange => "$(this).closest('form').submit();" %>
      </div>
    </a>

      <div class='thumb-description price-range'>
          <div class='text-left' id='label_min'>
              <p><%= prices.min.to_i %></p>
          </div>
          <div class='text-right' id='label_max'>
              <p><%= prices.max.to_i %></p>
          </div>
      </div>
</div>

<script>
  $(document).ready(function() {
      var slider = $("#slider").slider({
          range: true,
          min: <%= prices.min.to_i %>,
          max: <%= prices.max.to_i %>,
          values: [<%= prices.min.to_i %>, <%= prices.max.to_i %>],
          slide: function(event, ui) {
              $("#price_from").val(ui.values[0]);
              $("#price_to").val(ui.values[1]);
              $("#label_min").text(ui.values[0]);
              $("#label_max").text(ui.values[1]);
          }
      });
      $("#price_from").val(slider.slider("values")[0]);
      $("#price_to").val(slider.slider("values")[1]);

      $("#label_min").text(slider.slider("values")[0]);
      $("#label_max").text(slider.slider("values")[1]);
      $(".ui-slider-handle").focus();

      $('body').on('mouseup', '#slider', function() {
        $('#filter_form').submit();
       });
  });
</script>

app/views/sub_categories/_products.html.erb
<div class="flex thumbs-matrix-wrapper search-results-container" id="products_goes_here">
<% if products.count == 0 %>
  <div class="flash alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    Sorry, your search returned no products.
  </div>
<% else %>
  <% products.each do |product| %>

    <div class='thumb-wrapper'>
      <div class='flex thumb-header'>
        <span class='thumb-header-abbr'>
            <%= product.name && product.company && product.company.name %>
        </span>
        <span class='thumb-time-date'>
          <span class='glyphicon glyphicon-time'></span>
          <span>
            <%= product.created_at.strftime("%d %b %H:%M") %>
          </span>
        </span>

      </div>
        <%= link_to product do %>
          <div class='embed-responsive embed-responsive-16by9'>
            <%= image_tag product.picture.url, alt: product.name, class: 'img-responsive center-block' %>
          </div>
        <% end %>
        <div class='flex thumb-footer'>
          <span class='thumb-footer-model'>
            <%= link_to product do %>
              <%= product.name%> <%= "(#{product.year})" if product.year%>
            <% end %>
          </span>
          <div class='thumb-star-wrapper'>

            <%= product.actual_price.amount %>
            <%= product.prices.first.currency.sign %>
          </div>
        </div>
        <div class='thumb-description text-left'>
          <p>
            <%= truncate product.description, length: 110, separator: ' ' %>
          </p>
        </div>
        <div class='thumb-moreinfo-link'>
          <%= link_to 'More Info...', product %>
        </div>
    </div>

  <%end %>
<% end %>
</div>

app/views/sub_categories/_year_filter.html.erb
<div class="filter-wrapper">
    <a class='sub-filter-checkbox'>
      <label class="checkbox-style">
        <%= select_tag "year_from",
                                          options_for_select(years, :selected => params[:year_from]),
                                          prompt: 'from',
                                          :class => "check__form" %>


        <%= select_tag "year_to",
                                        options_for_select(years, :selected => params[:year_to]),
                                        prompt: 'to',
                                        :class => "check__form" %>

      </label>
    </a>
</div>

app/views/sub_categories/show.html.erb
<% content_for :messages do %>
  <%= render partial: 'layouts/messages', locals: { flash_class: 'floating' } %>
<% end %>

<% content_for :mobile_icons do %>
  <div class="mobile-burger-menu">
    <span></span><span></span><span></span>
  </div>
<!--  <div class="mobile-filter-button"></div>-->
<% end %>

<%= render 'filters_header' %>

<div class="main-container">

  <%= render 'left_filters' %>

  <!-- MAIN CONTENTS LAYOUT -->
  <main class="main-content-wrapper b-l-320">
    <div>


        <%= render partial: 'products', locals: { products: @products } %>

    </div>
  </main>
</div>

app/views/sub_categories/success.js.erb
(function() {

    var $html = $('<%=j render partial: "sub_categories/products", locals: { products: @products } %>');

    $('#products_goes_here').replaceWith($html);

}());