config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  namespace :admin do
    resources :users do
      resources :products
      resources :videos
      resources :photos
      resources :ratings
      resources :companies
      resources :reviews
    end
    resources :father_categories do
      resources :categories
    end
    resources :categories do
      resources :sub_categories
      resources :photos
      resources :videos
      resources :users
    end
    resources :sub_categories do
      resources :products
    end
    resources :companies do
      resources :products
      resources :users
    end
    resources :products do
      resources :videos
      resources :photos
      resources :prices
      resources :ratings
      resources :reviews
      resources :users
    end
    resources :videos do
      resources :users
    end
    resources :photos do
      resources :users
    end
    resources :distributors do
      resources :companies
    end
  end

  root to: 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users do
    collection do
      get :review
      get :photo
      get :video
    end
  end
  get 'ajax_destroy_recent_search', to: 'users#ajax_destroy_recent_search', as: :ajax_destroy_recent_search
  get 'ajax_destroy_favourite', to: 'users#ajax_destroy_favourite', as: :ajax_destroy_favourite
  get 'ajax_destroy_all_favourites', to: 'users#ajax_destroy_all_favourites', as: :ajax_destroy_all_favourites
  get 'ajax_destroy_recent_searches', to: 'users#ajax_destroy_recent_searches', as: :ajax_destroy_recent_searches
  get 'ajax_get_filter_options/:id' => 'products#set_filter_options', as: :set_filter_options

  resources :home, only: [:index]
  resources :search, only: [:index]
  resources :sub_categories, only: [:show]
  resources :products, only: [:show] do
    resources :reviews, only:[:new, :create], defaults: {format: :json}
    resources :user_favourite_products, only:[:add, :remove] do
      collection do
        get 'add'
        get 'remove'
      end
    end
  end

  resource :pictures, format: false, only: :create
  resources :photos, format: false, only: [:create, :show]
  resources :videos, format: false, only: [:create, :show]

  # controller :favourites, as: :favourite, path: :favourites,
  #            format: true, constraints: { format: :json } do
  #   %i(products photos videos).each do |type|
  #     defaults type: type do
  #       post type, to: :create
  #       delete type, to: :destroy
  #     end
  #   end
  # end

  post '/modals/:action', controller: :modals, format: false, as: :modals
  get '/modals/fetch' => 'modals#fetch', format: :json
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  include Recentable

  belongs_to :imageable, polymorphic: true

  has_attached_file :image, styles: { :subcatcover => '1500x844#', thumbnail: '250x190>' }
  validates_attachment :image, presence: true, content_type: { content_type: /\Aimage\/.*\Z/ }

  delegate :url, to: :image
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  include ImitateDelay
  imitate_delay only: :create
  before_filter :destroy_old_picture, only: :create

  def create
    picture = Picture.new creation_params
    if picture.save
      redirect_to edit_user_registration_path
    else
      render 'shared/errors', locals: { errors: picture.errors }
    end
  end

  private

  def creation_params
    params.require(:picture).permit %i(title imageable_type imageable_id image)
  end

  def destroy_old_picture
    old_picture = Picture.where(imageable_type: params[:picture][:imageable_type], imageable_id: params[:picture][:imageable_id]).last
    old_picture.destroy if old_picture
  end
end

app/views/pictures/_add.html.erb
<%= addendum_storage 'picture' %>

<%= form_for Picture.new, url: pictures_path, html: { multipart: true, class: 'form-horizontal' } do |form| %>

  <%= form.hidden_field :imageable_id,   value: params[:imageable_id] %>
  <%= form.hidden_field :imageable_type, value: params[:imageable_type] %>

  <div class='form-group'>
    <%= form.label :title, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= form.label :image, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= form.file_field :image, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <div class='col-sm-offset-2 col-sm-10'>
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/pictures/_thumbnail.html.erb
<a href='#' class='enlarge-image'>
  <%= image_tag picture.url(:thumbnail), alt: '', data: { src: picture.url },
                class: 'img-responsive center-block img-thumbnail' %>
</a>