config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  namespace :admin do
    resources :users do
      resources :products
      resources :videos
      resources :photos
      resources :ratings
      resources :companies
      resources :reviews
    end
    resources :father_categories do
      resources :categories
    end
    resources :categories do
      resources :sub_categories
      resources :photos
      resources :videos
      resources :users
    end
    resources :sub_categories do
      resources :products
    end
    resources :companies do
      resources :products
      resources :users
    end
    resources :products do
      resources :videos
      resources :photos
      resources :prices
      resources :ratings
      resources :reviews
      resources :users
    end
    resources :videos do
      resources :users
    end
    resources :photos do
      resources :users
    end
    resources :distributors do
      resources :companies
    end
  end

  root to: 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users do
    collection do
      get :review
      get :photo
      get :video
    end
  end
  get 'ajax_destroy_recent_search', to: 'users#ajax_destroy_recent_search', as: :ajax_destroy_recent_search
  get 'ajax_destroy_favourite', to: 'users#ajax_destroy_favourite', as: :ajax_destroy_favourite
  get 'ajax_destroy_all_favourites', to: 'users#ajax_destroy_all_favourites', as: :ajax_destroy_all_favourites
  get 'ajax_destroy_recent_searches', to: 'users#ajax_destroy_recent_searches', as: :ajax_destroy_recent_searches
  get 'ajax_get_filter_options/:id' => 'products#set_filter_options', as: :set_filter_options

  resources :home, only: [:index]
  resources :search, only: [:index]
  resources :sub_categories, only: [:show]
  resources :products, only: [:show] do
    resources :reviews, only:[:new, :create], defaults: {format: :json}
    resources :user_favourite_products, only:[:add, :remove] do
      collection do
        get 'add'
        get 'remove'
      end
    end
  end

  resource :pictures, format: false, only: :create
  resources :photos, format: false, only: [:create, :show]
  resources :videos, format: false, only: [:create, :show]

  # controller :favourites, as: :favourite, path: :favourites,
  #            format: true, constraints: { format: :json } do
  #   %i(products photos videos).each do |type|
  #     defaults type: type do
  #       post type, to: :create
  #       delete type, to: :destroy
  #     end
  #   end
  # end

  post '/modals/:action', controller: :modals, format: false, as: :modals
  get '/modals/fetch' => 'modals#fetch', format: :json
end

app/models/product.rb
class Product < ActiveRecord::Base
  include Recentable

  belongs_to :company
  belongs_to :sub_category, inverse_of: :products
  has_one :category, through: :sub_category

  has_many :videos
  has_many :photos
  has_many :prices
  has_many :attrs, class_name: "Attribute"
  has_many :ratings
  has_many :reviews
  has_many :dimensions
  has_many :user_favourites, as: :favouriteable
  has_many :users, through: :user_favourites
  has_many :pictures, as: :imageable
  has_many :similars, -> (p) { where.not(id: p) }, through: :sub_category, source: :products
  has_and_belongs_to_many :filter_options

  has_one :actual_price, -> { order created_at: :asc }, class_name: 'Price' # .actual_price method

  alias_attribute :characteristics, :attrs # .characteristics method

  delegate :name, to: :company, prefix: true # .company_name method
  delegate :name, to: :sub_category, prefix: true # .sub_category_name method
  delegate :count, to: :photos, prefix: true # .photos_count method
  delegate :count, to: :videos, prefix: true # .videos_count method
  delegate :count, to: :similars, prefix: true # .similars_count method
  delegate :distributors, to: :company, allow_nil: true # .distributors method

  accepts_nested_attributes_for :attrs, allow_destroy: true
  accepts_nested_attributes_for :prices, allow_destroy: true
  accepts_nested_attributes_for :dimensions, allow_destroy: true
  accepts_nested_attributes_for :pictures, allow_destroy: true

  scope :filter, ->(filters) { includes(:filter_options)
                              .where(filter_options: { id: filters }) if filters.present? }

  scope :companies, ->(companies) { where(company_id: companies ) if companies.present? }
  scope :year_from, ->(year_from) { where('year >= ?', year_from ) if year_from.present? }
  scope :year_to, ->(year_to) { where('year <= ?', year_to ) if year_to.present? }
  scope :price_from, ->(price_from) { joins(:actual_price).where('prices.amount >= ?', price_from ) if price_from.present? }
  scope :price_to, ->(price_to) { joins(:actual_price).where('prices.amount <= ?', price_to ) if price_to.present? }

  def title
    "#{name} - #{sub_category_name}"
  end

  def date_string
    created_at.to_date.to_s(:rfc822)
  end

  def price_string
    prices.first.try(:title) # TODO: select a proper price record
  end

  def rating
    [ratings.average(:value).to_i, 5].min
  end

  def picture
    pictures.recent.first || default_picture
  end

  def picture_url *args
    args.clear if picture == default_picture
    picture.url *args
  end

  def self.media
    media = []
    media += Photo.where(product_id:self.ids)
    media += Video.where(product_id:self.ids)
    media += Review.where(product_id:self.ids)
    media
  end

  cattr_reader :default_picture do
    OpenStruct.new url: 'thumb-img-1.png', title: 'No images found'
  end
  default_picture.deep_freeze

  def self.base_search(search, sub_categories, companies)
    prods = all
    if search || sub_categories.is_a?(Array) || companies.is_a?(Array)
      prods = prods.where('lower(products.name) LIKE lower(:search) or lower(products.description) LIKE lower(:search)', search: "%#{search}%") if search
      prods = prods.where(sub_category_id: sub_categories) if sub_categories.is_a?(Array)
      prods = prods.where(company_id: companies) if companies.is_a?(Array)
      prods
    end
    prods
  end

  def self.search( search, sub_categories, companies, start_row_index, take_count )
    prods = self.base_search( search, sub_categories, companies ).offset( start_row_index ).limit( take_count )
  end

  def self.search_count( search, sub_categories, companies )
    prods = self.base_search( search, sub_categories, companies ).count
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include HelperAttr
  helper_attr :product, :pictures, :reviews, :photos, :videos, :similars
  before_action :set_product, only:[:show]

  def show
    @pictures = product.pictures.recent.first(6)
    @reviews = product.reviews.recent.first(3)
    @simpage = (params[:similar] || '1').to_i
    if @simpage == 1
      @similars = Kaminari.paginate_array(product.similars.recent)
                     .page(@simpage)
                     .per(2)
    else
      @similars = Kaminari.paginate_array(product.similars.recent)
                     .page(@simpage)
                     .per(10).padding(-8)
    end
    @photopage = (params[:photo] || '1').to_i
    if @photopage == 1
      @photos = Kaminari.paginate_array(product.photos.recent)
                     .page(@photopage)
                     .per(2)
    else
      @photos = Kaminari.paginate_array(product.photos.recent)
                     .page(@photopage)
                     .per(10).padding(-8)
    end
    @videopage = (params[:video] || '1').to_i
    if @videopage == 1
      @videos = Kaminari.paginate_array(product.videos.recent)
                     .page(@videopage)
                     .per(2)
    else
      @videos = Kaminari.paginate_array(product.videos.recent)
                     .page(@videopage)
                     .per(10).padding(-8)
    end
    if request.xhr?
      if params[:similar]
        render partial: 'product_similar', locals: { results: @similars }
      end
      if params[:photo]
        render partial: 'product_photo', locals: { results: @photos }
      end
      if params[:video]
        render partial: 'product_video', locals: { results: @videos }
      end

    else
      render
    end
  end

    def set_filter_options
      @product = Product.find(params[:product_id]) if params[:product_id].present?

      sub_category = SubCategory.find(params[:id])
      @filter_options = sub_category.filter_options

      respond_to do |format|
         format.html { render :layout => false }
         format.js {}
      end
    end

  private

  def set_product
    @product = Product.find params[:id]
  end
end

app/views/products/_breadcrumbs.html.erb
<ol class='breadcrumb'>
  <li>
    <%= link_to 'Home', root_path %>
  </li>
  <li>
    <%= link_to product.sub_category_name,
                search_index_path(sub_categories: [product.sub_category_id]) %>
  </li>
  <li>
    <%= link_to product.company_name,
                search_index_path(sub_categories: [product.sub_category_id],
                                  companies: [product.company_id]) %>
  </li>
  <li class='active'>
    <%= link_to product.name, product %>
  </li>
</ol>

app/views/products/_characteristic.html.erb
<h1>
  <%= "#{characteristic.title}:" %>
</h1>
<p>
  <%= characteristic.value %>
</p>

app/views/products/_company.html.erb
<h1>
  <%= company.name %>
  <small class='pull-right'>
    <%= link_to company.url, company.url, :target => "_blank" %>
  </small>
</h1>
<p>
  <%= company.description %>
</p>
<h2>Contacts:</h2>
<address>
  <% if company.email? %>
    <p>
      <strong>Contact Email: </strong><%= company.email %>
    </p>
  <% end %>
  
  <% unless company.address == nil %>
    <p>
      <strong>Address: </strong><%= company.address.street %> <%= company.address.city %> <%= company.address.postcode %>
    </p>
  <% end %>
  
  
  <% if company.phone? %>
    <p>
      <strong>Contact Phone: </strong><%= company.phone %>
    </p>
  <% end %>
  
  <% if company.fax? %>
    <p>
      <strong>Contact Fax: </strong><%= company.fax %>
    </p> 
  <% end %>
  
</address>

app/views/products/_distributor.html.erb
<h1>
  <%= distributor.information %>
  <small class='pull-right'>
    <%= link_to distributor.url, distributor.url %>
  </small>
</h1>
<address>
  <% if distributor.email? %>
    <p>
      <strong>Contact Email: </strong><%= distributor.email %>
    </p>
  <% end %>
  
  <% unless distributor.address == nil %>
    <p>
      <strong>Address :</strong><%= distributor.address.street %> <%= distributor.address.city %> <%= distributor.address.postcode %>
    </p>
  <% end %>
  
  
  <% if distributor.phone? %>
    <p>
      <strong>Contact Phone: </strong><%= distributor.phone %>
    </p>
  <% end %>

</address>

app/views/products/_product_photo.html.erb
<%= photo_thumbnails photos  %>
<div class="hidden photo-have-more" data-hasmore="<%= @photos.next_page %>"></div>

app/views/products/_product_similar.html.erb
<%= product_thumbnails similars  %>
<div class="hidden similar-have-more" data-hasmore="<%= @similars.next_page %>"></div>

app/views/products/_product_video.html.erb
<%= video_thumbnails videos  %>
<div class="hidden video-have-more" data-hasmore="<%= @videos.next_page %>"></div>

app/views/products/_rating.html.erb
<% (1..5).each do |point| %>
  <span class='glyphicon glyphicon-star rating-point<%= '-empty' if point > rating %>'></span>
<% end %>

app/views/products/_reviews.html.erb
<div id='reviews-carousel' class='carousel slide' data-ride='carousel'>
  <ol class='carousel-indicators'>
    <% reviews.each_index do |index| %>
      <li data-target='#reviews-carousel' data-slide-to='<%= index %>'
          class='<%= 'active' if index.zero? %>'></li>
    <% end %>
  </ol>
  <div class='carousel-inner' role='listbox'>
    <% reviews.each_with_index do |review, index| %>
      <div class='item <%= 'active' if index.zero? %> text-center'>
        <h1>
          <%= review.title %>
        </h1>
        <h2>
          <%= review.review %>
        </h2>
        <p>
          <%= render partial:'rating', locals:{rating: review.rating && review.rating.value || 0} %>
          &nbsp;
          <%= review.user_name %> - <%= review.date_string %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_thumbnail.html.erb
<div class='thumb-wrapper'>
  <div class='flex thumb-header'>
    <span class='thumb-header-abbr'>
      <%= product.sub_category_name %>
    </span>
    <span class='thumb-time-date'>
      <span class='glyphicon glyphicon-time'></span>
      <span>
        <%= product.date_string %>
      </span>
    </span>
  </div>
    <div class='thumb-image'>
      <%= image_tag product.picture_url(:thumbnail), alt: '' %>
    </div>
    <div class='flex thumb-footer'>
      <span class='thumb-footer-model'>
        <%= product.name %>
      </span>
      <div class='thumb-star-wrapper'>
        <%= render 'products/rating', rating: product.rating %>
      </div>
    </div>
    <div class='thumb-description text-left'>
      <p>
        <%= truncate product.description, length: 110, separator: ' ' %>
      </p>
    </div>
    <div class='thumb-moreinfo-link'>
      <%= link_to 'More Info...', product %>
    </div>
</div>

app/views/products/set_filter_options.html.erb
<li class="check_boxes input optional" id="product_filter_options_input">
    <fieldset class="choices">
        <legend class="label">
            <label>Filter Options</label>
        </legend>
        <input type="hidden" name="product[filter_option_ids][]" id="product_filter_options_none" value="">


        <ol class="choices-group">
            <% @filter_options.each do |filter_option| %>
                <li class="choice">
                    <label for="product_filter_option_ids_<%= filter_option.id %>">
                        <% if @product %>
                            <% if @product.filter_options.include? filter_option %>
                                <input type="checkbox"
                                       checked="checked"
                                       name="product[filter_option_ids][]"
                                       id="product_filter_option_ids_<%= filter_option.id %>"
                                       value="<%= filter_option.id %>">
                                <%= filter_option.name  %>
                            <% else %>
                                <input type="checkbox"
                                       name="product[filter_option_ids][]"
                                       id="product_filter_option_ids_<%= filter_option.id %>"
                                       value="<%= filter_option.id %>">
                                <%= filter_option.name  %>
                            <% end %>
                        <% else %>
                            <input type="checkbox"
                                   name="product[filter_option_ids][]"
                                   id="product_filter_option_ids_<%= filter_option.id %>"
                                   value="<%= filter_option.id %>">
                            <%= filter_option.name  %>
                        <% end %>
                    </label>
                </li>
            <% end %>
        </ol>
    </fieldset>
</li>

app/views/products/show.html.erb
<div class='main-container'>
  <main class='main-content-wrapper'>
    <%= render 'breadcrumbs' %>
    <div class='page-header'>
      <h1>
        <%= product.name %>
      </h1>
    </div>
    <div class='container-fluid'>
      <div class='row'>
        <div class='col-md-2 visible-md visible-lg'>
          <%= picture_thumbnails pictures %>
          <% 5.times do %>
            <%= image_tag product.picture_url, alt: '', class: 'product-image-small' %>
          <% end %>
        </div>
        <div class='col-md-10'>
          <%= image_tag product.picture_url, alt: '', id: 'large-image', class: 'img-responsive center-block' %>
        </div>
      </div>
    </div>
  </main>
  <aside class='side-panel-wrapper'>
    <div class='product-brief'>
      <h1>
        Price: <%= product.price_string %>
      </h1>
      <p>
        <%= render 'rating', rating: product.rating %>
      </p>
      <% if product.url.present? %>
        <p>
          <%= link_to 'Product Website', product.url, :target => "_blank" %>
        </p>
      <% end %>
      <p>
        <% if user_signed_in? %>
          <% if product.users.include? current_user %>
            Added to Favourites <%= link_to '(Remove)', remove_product_user_favourite_products_path(@product) %>
          <% else %>
            <%= link_to 'Add to Favourites', add_product_user_favourite_products_path(@product) %>
          <% end %>
        <% end %>
      </p>
    </div>
  </aside>
</div>

<!-- description section -->
<div class='product-description text-center'>
  <%= product.description %>
</div>

<!-- reviews section -->
<div class='product-reviews'>
  <%= render 'reviews', reviews: reviews unless reviews.empty? %>
  <div class='buttons text-center'>
    <%= link_to 'Read More Reviews', '#', class: 'btn btn-default', role: 'button' %>
    <%= modal_button_tag 'Add a review',
        new_product_review_path(@product),
        method: :get,
        link: true,
        class:'btn btn-default' %>
  </div>
</div>

<!-- photos section -->
<div class='product-assets product-photos text-center'>
  <h1>Latest photos of <%= product.name %></h1>
  <div class="main-container">
    <div class="main-content-wrapper">
      <div class="flex thumbs-matrix-wrapper photo-wrapper">
        <%= render partial: 'product_photo', locals: { results: @photos } %>
      </div>
    </div>
  </div>
  <div class='buttons' id="show-photo">
    <%= link_to "Show more (#{product.photos_count - 2})",
                product_path(product, photo: @photos.next_page),
                { class: 'btn btn-default', role: 'button', 'data-remote': true}  %>
    <% if user_signed_in? %>
      <%= modal_button_tag 'Upload', modals_path(action: :add_photo),
                           class: 'btn btn-success pull-right',
                           product_id: product.id %>
    <% end %>
  </div>
</div>

<!-- videos section -->
<div class='product-assets product-videos text-center'>
  <h1>Latest videos of <%= product.name %></h1>
  <div class="main-container">
    <div class="main-content-wrapper">
      <div class="flex thumbs-matrix-wrapper video-wrapper">
        <%= render partial: 'product_video', locals: { results: @videos } %>
      </div>
    </div>
  </div>    <div class='buttons' id="show-video">
        <%= link_to "Show more (#{product.videos_count - 2})",
                    product_path(product, video: @videos.next_page),
                    { class: 'btn btn-default', role: 'button', 'data-remote': true}  %>
    <% if user_signed_in? %>
      <%= modal_button_tag 'Upload', modals_path(action: :add_video),
                           class: 'btn btn-success pull-right',
                           product_id: product.id %>
    <% end %>
  </div>
</div>

<!-- details section -->
<div class='product-assets product-details text-center'>
  <div>
    <ul class='nav nav-pills' role='tablist'>
      <li role='presentation' class='active'>
        <a href='#characteristics' aria-controls='characteristics' role='tab' data-toggle='pill'>
          Characteristics
        </a>
      </li>
      <li role='presentation'>
        <a href='#company' aria-controls='company' role='tab' data-toggle='pill'>
          Company
        </a>
      </li>
      <li role='presentation'>
        <a href='#distributors' aria-controls='distributors' role='tab' data-toggle='pill'>
          Where to buy it
        </a>
      </li>
    </ul>
    <div class='tab-content container text-left'>
      <div role='tabpanel' class='tab-pane active' id='characteristics'>
        <%= render partial: 'characteristic', collection: product.characteristics %>
        <% unless product.dimensions.empty? %>
          <h1>Dimensions:</h1>
          <% product.dimensions.each do |dimension| %>
            <p><%= dimension.text %></p>
          <% end %>
        <% end %>
      </div>
      <div role='tabpanel' class='tab-pane' id='company'>
        <%= render 'company', company: product.company if product.company %>
      </div>
      <div role='tabpanel' class='tab-pane' id='distributors'>
        <%= render partial: 'distributor', collection: product.distributors %>
      </div>
    </div>
  </div>
</div>

<!-- similar products section -->
<div class='product-assets product-similars text-center'>
  <h1>Similar Products</h1>
  <div class="main-container">
    <div class="main-content-wrapper">
      <div class="flex thumbs-matrix-wrapper similar-wrapper">
        <%= render partial: 'product_similar', locals: { results: @similars } %>
      </div>
    </div>
  </div>
  <div class='buttons' id="show-similar">
    <%= link_to "Show more (#{product.similars_count - 2})",
                product_path(product, similar: @similars.next_page),
                { class: 'btn btn-default', role: 'button', 'data-remote': true}  %>
  </div>
</div>